### ISSUE TITLE
Does not work with Rails 4.2.8?

### ISSUE THREAD

**Issue by arthurzhou** [coup-mobility/activesupport-current_attributes#5]
$rails c
/.rvm/gems/ruby-2.4.3/gems/activesupport-current_attributes-0.0.2/lib/active_support/current_attributes/railtie.rb:6:in `block in <class:Railtie>': undefined method `reloader' for #<R::Application:0x00007fbd639f10a0> (NoMethodError)
Did you mean?  reloaders

**Comment by djhopper01** [comment]
Just to add some more information, I'm getting the same error using Rails 4.2.10. I'm wondering if I'm missing something and that's why it's not working as intended.

```
NoMethodError: undefined method `reloader'
```

I started looking into the Railtie on [Line 6](https://github.com/coup-mobility/activesupport-current_attributes/blob/master/lib/active_support/current_attributes/railtie.rb#L6).

```ruby
app.reloader.before_class_unload { ActiveSupport::CurrentAttributes.clear_all }
```

I believe `app` is referring to Rails::Application in this case. I did some digging into reloader which is referenced. It doesn't appear to be available in Rails 4.2.x. It looks like it was first introduced in Rails 5.0.0 (https://github.com/rails/rails/blob/2efddadd6cba4e2129acedf1d402d11abcc03996/railties/lib/rails/application.rb#L133).

@ahazem is there maybe something I'm missing? Thanks for putting this together. I'll keep investigating and let you know what I find.

**Comment by gregblass** [comment]
Apologies to be the +1 to this thread, but I just tried adding this gem to an older client project since it says >= 4.2 in the docs. Experiencing the same problem here. Was anyone able to get this gem working with Rails 4.2.8?

**Comment by gregblass** [comment]
Wouldn't this render this entire library basically useless if it doesn't work with 4.2.8 or 4.2.10? Seems like that exactly what it's purpose is.

**Comment by rdunlop** [comment]
On Rails 4.2.10, I just added the contents of https://github.com/coup-mobility/activesupport-current_attributes/blob/master/lib/active_support/current_attributes/current_attributes.rb to a `config/initializers/current_attributes.rb` file, and it appears to be working properly.

I don't know whether this is going to bite me if I'm doing development with auto-reloading, but so far, so good.

**Comment by rolo9128** [comment]
Sorry to revive this thread but I'm having the same problem with Rails 4.2.6. I tried rdunlop's solution right above this to no avail. Has anyone else made any progress with this issue?
